-- ================================
-- EXPLORATORY DATA ANALYSIS
-- ================================

SELECT * FROM retail_sales;
DESC retail_sales; -- viewing meta data details

-- Dimension column Exploration 
-- -------------------------------
/*#Dim_columns ->
transactions_id, 
customer_id, 
gender, 
Category
*/

SELECT DISTINCT gender 
FROM retail_sales
;

SELECT DISTINCT category
FROM retail_sales
;

-- Date & Time column Exploration
-- ----------------------------------
/* Date & Time columns ->
sale_date, 
sale_time, 
*/

SELECT -- date exploration
	MIN(sale_date) AS starting_date
    , MAX(sale_date) AS latest_date
    , TIMESTAMPDIFF(YEAR, MIN(sale_date), MAX(sale_date)) AS sales_range_years
FROM retail_sales
;

SELECT -- time exploration
    MIN(sale_time) AS earliest_time,
    MAX(sale_time) AS latest_time
FROM retail_sales
;

-- Measure Column Exploration 
-- ------------------------------
/* #Measure_columns -> 
age, 
quantity, 
price_per_unit, 
cogs, 
total_sales
*/
SELECT * FROM retail_sales;
-- total_sales
SELECT 
	SUM(total_sale) AS total_sales
    , SUM(quantity) AS total_quantity_sold
FROM retail_sales;
-- average selling price
SELECT ROUND(SUM(total_sale) / SUM(quantity),2) AS avg_selling_price
FROM retail_sales;

-- Magnitude Analysis:-
-- --------------------------------
-- 1) Find total customer by gender
SELECT 
	gender
    , COUNT(customer_id) AS total_customers
FROM retail_sales
GROUP BY gender;
-- 2) Find total customer by category
SELECT 
	category
    , COUNT(customer_id) AS total_customers
FROM retail_sales
GROUP BY category;
-- 3) What is the average sales in each category?
SELECT 
	category
    , ROUND(AVG(total_sale),2) AS avg_sales
FROM retail_sales
GROUP BY category;
-- 4) What is the total revenue generated for each category?
SELECT 
	category
    , SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY category;
-- 5) Find total revenue is generated by each customer?
SELECT 
	customer_id
    , SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY customer_id
ORDER BY total_revenue DESC;

-- 6) What is the distribution of items sold across category?
SELECT 
	category
    , SUM(quantity) AS total_sold_items
FROM retail_sales
GROUP BY category
ORDER BY total_sold_items DESC;

-- Ranking Analysis:-
-- --------------------------------
-- 1) Which 5 customer generate the highest revenue?

WITH ranked_cus AS (
SELECT 
	customer_id
    , SUM(total_sale) AS total_spent
    , DENSE_RANK() OVER(ORDER BY SUM(total_sale) DESC) AS rn
FROM retail_sales
GROUP BY customer_id
)
SELECT 
	customer_id
    , total_spent
FROM ranked_cus
WHERE rn <= 5
;

-- 2) What are the 5 worst-performing weeks in terms of sale

WITH ranked_days AS (
SELECT 
	MONTHNAME(MIN(sale_date)) AS 'month'
	, WEEK(sale_date) AS 'week'
    , SUM(total_sale) AS sold_amount
    , DENSE_RANK() OVER(ORDER BY SUM(total_sale)) AS rn
FROM retail_sales
GROUP BY week
)
SELECT 
	month
	, week
    , sold_amount
FROM ranked_days
WHERE rn <= 5
;

